app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# coding=utf-8
from flask import abort, flash, redirect, render_template, url_for, request, jsonify
from flask_login import login_required, current_user, logout_user
from ..models import Student, Teacher, Experiment, Course
from . import home
from .. import db
from ..auth.forms import UpdateForm
from werkzeug.security import generate_password_hash
import json

from ..models import Container


# @home.route('/dashboard', methods=['GET', 'POST'])
# @login_required
# def dashboard():
#     return render_template('home/dashboard.html', title='Dashboard')


@home.route('/teacher/dashboard')
@login_required
def teacher_dashboard():
    if not current_user.isTeacher:
        abort(403)
    students = Student.query.all()
    return render_template('home/teacher_dashboard.html', students=students)


@home.route('/list_courses', methods=['GET', 'POST'])
@login_required
def list_courses():
    courses = Student.query.filter_by(name=current_user.name).first().courses
    experimentSet = []
    for i in courses:
        experiments = Experiment.query.filter_by(courseNums=i.courseNums).all()
        experimentSet.append(experiments)
    # return render_template('home/list_courses.html', title='Student Classes', courses=courses,
    # experimentSet=experimentSet)
    return render_template('home/list_courses.html', courses=courses, experimentSet=experimentSet,
                           name=current_user.realname)


@home.route('/selectCourseForm', methods=['GET', 'POST'])
@login_required
def selectCourseForm():
    return render_template('home/select_course.html')


@home.route('/selectCourse', methods=['GET', 'POST'])
@login_required
def selectCourse():  # 查询表单提交处理函数
    nums = request.form['nums']
    course = Course.query.filter_by(courseNums=nums).first()
    if course:
        try:
            current_user.courses.append(course)
            db.session.commit()
            flash(u'选课成功')
            return redirect(url_for('home.list_courses'))
        except:
            flash(u'选课失败，可能是您已经拥有该门课程')
            return redirect(url_for('home.list_courses'))
    else:
        flash(u'选课码无效')
        return redirect(url_for('home.selectCourseForm'))


@home.route('/experiment/<string:id>', methods=['GET', 'POST'])
@login_required
def experiment(id):
    experiment = Experiment.query.filter_by(id=id).first()
    return render_template('pwd/index.html', content=experiment.content,
                           containerName=experiment.containerName,
                           isTeacher=0, title='terminal online')


@home.route('/update_infos', methods=['GET', 'POST'])
@login_required
def update_infos():
    form = UpdateForm()
    if form.validate_on_submit():
        student = Student.query.filter_by(name=current_user.name).first()
        student.realname = form.realname.data
        student.password_hash = generate_password_hash(form.password.data)
        db.session.commit()
        db.session.close()
        logout_user()
        return redirect(url_for('auth.login'))
    return render_template('home/update_infos.html', name=current_user.realname, form=form)


@home.route('/images/search', methods=['GET', 'POST'])
def images_search():
    imageName = json.loads(request.get_data())
    imageNames = []
    for i in Container.query.filter(Container.name.like('%' + imageName['term'] + '%')).all():
        imageNames.append(i.name)
    return jsonify(imageNames)

app/templates/home/dashboard.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Hello {{current_user.name}}</h1>
                    <h3>Welcome to Hangdian. Let's Get Started</h3>
                    </ul>
                    <br>
                    <br>
                    <a href="{{ url_for('home.list_courses') }}" id="profilebtn">View your courses</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block body %}
<p id="message">
    Just for a test
</p>
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Hangdian</h1>
                    <h3>Manage courses in the most perfect way</h3>
                    </ul>
                    <br>
                    <br>
                    <a href="{{ url_for('auth.register') }}" id="out">New User? Let's Get Started!</a>
                    <br>
                    <br>
                    <br>
                    <a href="{{ url_for('auth.login_teacher') }}" id="in">Teacher Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/list_courses.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block metas %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{% endblock metas %}

    {% block title %}{{ super() }}{% endblock title %}

{% block styles %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='content-static/bootstrap.css') }}" rel="stylesheet">
<!--<link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet">-->
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='content-static/offcanvas.css') }}" rel="stylesheet">
{% endblock styles %}

{% block navbar %}
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <!--<li class="nav-item active">-->
            <!--<a class="nav-link" href="#">已选课程 <span class="sr-only">(current)</span></a>-->
          <!--</li>-->
          <!--<li class="nav-item">-->
            <!--<a class="nav-link" href="#">我要选课</a>-->
          <!--</li>-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ name }}</a>
            <div id="mydropdown" class="dropdown-menu" aria-labelledby="Preview" style="min-width:0rem;">
				<a class="dropdown-item" href="#">已选课程</a>
                <a class="dropdown-item" href="{{ url_for('home.selectCourseForm') }}">我要选课</a>
				<a class="dropdown-item" href="{{ url_for('home.update_infos') }}">修改信息</a>
				<a class="dropdown-item" href="{{ url_for('auth.logout') }}">退出登录</a>
            </div>
          </li>
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" placeholder="Search" aria-label="Search" type="text">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>
{% endblock navbar %}

{% block page_content %}

    <div class="container marketing">
        <div class="jumbotron jumbotron-fluid">
          <h1 class="display-3">Hdu Online Laboratory!</h1>
          <br><p class="lead">这是一个在线实验平台，你可以在这里选择相应的实验进行操作。</p>
        </div>


      <div class="row">
          {% if courses.all() %}
            {% for course in courses %}
          <div class="col-lg-4">
              <div class="card">
                  <h4 class="card-header">{{course.name}}</h4>
                  <div class="card-body">
                    <p class="card-text">{{course.description}}</p>
                  </div>
                  {% if experimentSet %}
                  <ul class="list-group list-group-flush">
                      {% for experiment in experimentSet[loop.index0] %}
                      <li class="list-group-item"><a class="btn" href="{{ url_for('home.experiment',id=experiment.id) }}">{{ experiment.name }}</a></li>
                      {% endfor %}
                  </ul>
                  {% endif %}
              </div>
          </div>
          {% endfor %}

          {% endif %}
          <div class="col-lg-4">
              <div class="card">
                  <h4 class="card-header">选课</h4>
                  <div class="card-body">
                    <p class="card-text">你可以点击下面的“我要选课”按钮，输入选课口令即可选择相应课程</p>
                    <p><a class="btn btn-primary btn-lg" href="{{ url_for('home.selectCourseForm') }}">我要选课</a></p>
                  </div>
              </div>
          </div>
      </div><!-- /.row -->
    </div><!--/.container-->

{% endblock page_content %}

app/templates/home/list_courses_old.html
{% extends "base.html" %} {% block title %}View Courses{% endblock %} {% block body %}
<div id="mainwrap">
    <!-- <img src="../../static/img/avatar.png" id="avatar"> -->
    <p id="cname">{{current_user.name}} </p>
    <!-- add the course button -->
    <form action="{{ url_for('home.selectCourse') }}" method="POST">
        <input type="text" name="nums">
        <input type="submit" name="submit">
    </form>
    {% if courses %}
    {% for i in courses %}
        <ul>{{ i.name }}</ul>
        {% for j in experimentSet[loop.index0] %}
             <li><a href="{{ url_for('home.experiment',name=j.name) }}">{{ j.name }}</a></li>
        {% endfor %}
    {% endfor %}
    {% else %}
    <h1>No course selected yet !</h1>
    {% endif %}
</div>
{% endblock %}

app/templates/home/select_course.html
{% extends "base.html" %}

{% block metas %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{% endblock metas %}

    {% block title %}{{ super() }}{% endblock title %}

{% block styles %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='content-static/bootstrap.css') }}" rel="stylesheet">
<!--<link href="{{ url_for('static', filename='bootstrap.css') }}" rel="stylesheet">-->
    <!-- Custom styles for this template -->
    <link href="{{ url_for('static', filename='content-static/offcanvas.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='content-static/select_course.css') }}" rel="stylesheet">
{% endblock styles %}

{% block navbar %}
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <!--<li class="nav-item active">-->
            <!--<a class="nav-link" href="#">已选课程 <span class="sr-only">(current)</span></a>-->
          <!--</li>-->
          <!--<li class="nav-item">-->
            <!--<a class="nav-link" href="#">我要选课</a>-->
          <!--</li>-->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ current_user.realname }}</a>
            <div id="mydropdown" class="dropdown-menu" aria-labelledby="Preview" style="min-width:0rem;">
                <a class="dropdown-item" href="{{ url_for('home.list_courses') }}">已选课程</a>
				<a class="dropdown-item" href="#">我要选课</a>
				<a class="dropdown-item" href="{{ url_for('home.update_infos') }}">修改信息</a>
				<a class="dropdown-item" href="{{ url_for('auth.logout') }}">退出登录</a>
            </div>
          </li>
        </ul>
        <!--<form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" placeholder="Search" aria-label="Search" type="text">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>-->
      </div>
    </nav>
{% endblock navbar %}

{% block page_content %}

   <div class="container">

      <form action="/selectCourse" class="form-signin" method="POST">
        <h5 class="form-signin-heading">输入选课口令即可选择相应课程</h5>
        <label for="inputCode" class="sr-only"></label>
        <input name="nums" type="text" id="inputCode" class="form-control" placeholder="选课口令" required="">
          <input class="btn btn-outline-success my-2 my-sm-0" type="submit" value="确认"/>
      </form>



    </div> <!-- /container -->


{% endblock page_content %}

{% block scripts %}
    {{ super() }}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='content-static/ie10-viewport-bug-workaround.js') }}"></script>
{% endblock scripts %}

app/templates/home/teacher_dashboard.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block metas %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{% endblock metas %}

{% block styles %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="{{ url_for('static', filename='content-static/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='dashboard.css') }}" rel="stylesheet">
{% endblock styles %}

{% block navbar %}
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">{{ current_user.realname }}</a>
            <div id="mydropdown" class="dropdown-menu" aria-labelledby="Preview" style="min-width:0rem;">
				<a class="dropdown-item" href="{{ url_for('admin.update_infos') }}">修改信息</a>
				<a class="dropdown-item" href="{{ url_for('auth.logout') }}">退出登录</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
{% endblock navbar %}

{% block page_content %}
        <div class="container-fluid">
      <div class="row">
        <nav class="col-sm-3 col-md-2 d-none d-sm-block bg-light sidebar">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              <a class="nav-link active" href="">所有学生名单 <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.list_courses') }}">我的课程</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('admin.list_experiments') }}">我的实验</a>
            </li>
          </ul>
        </nav>

        <main class="col-sm-9 ml-sm-auto col-md-10 pt-3" role="main">
          <h1>学生花名册</h1>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>学号</th>
                  <th>姓名</th>
                  <th>修改信息</th>
                  <th>删除账号</th>
                </tr>
              </thead>
              <tbody>
              {% for student in students %}
                <tr>
                  <td>{{ student.name }}</td>
                  <td>{{ student.realname }}</td>
                  <td>
                      <a href="{{ url_for('admin.edit_account', name=student.name) }}" class="">
                      Edit
                      </a>
                  </td>
                  <td>
                      <a href="{{ url_for('admin.delete_account', name=student.name) }}" class="">
                      Delete
                      </a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </main>
      </div>
    </div>
{% endblock page_content %}

{% block scripts %}
    {{ super() }}
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{{ url_for('static', filename='content-static/ie10-viewport-bug-workaround.js') }}"></script>
{% endblock scripts %}

app/templates/home/teacher_dashboard_old.html
{% extends "base.html" %} {% block title %}Teacher Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Teacher Dashboard</h1>
                    <br>
                    <br>
                    <a href="{{ url_for('admin.list_courses') }}" id="db">Your Courses</a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/update_infos.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block metas %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
{% endblock metas %}

    {% block title %}{{ super() }}{% endblock title %}

{% block styles %}
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static', filename='content-static/bootstrap.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='content-static/offcanvas.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='content-static/select_course.css') }}" rel="stylesheet">
{% endblock styles %}

{% block navbar %}
    {% if not current_user.isTeacher %}
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ current_user.realname }}</a>
            <div id="mydropdown" class="dropdown-menu" aria-labelledby="Preview" style="min-width:0rem;">
                <a class="dropdown-item" href="{{ url_for('home.list_courses') }}">已选课程</a>
				<a class="dropdown-item" href="{{ url_for('home.selectCourseForm') }}">我要选课</a>
				<a class="dropdown-item" href="#">修改信息</a>
				<a class="dropdown-item" href="{{ url_for('auth.logout') }}">退出登录</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% else %}
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-dark">
      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">{{ current_user.realname }}</a>
            <div id="mydropdown" class="dropdown-menu" aria-labelledby="Preview" style="min-width:0rem;">
				<a class="dropdown-item" href="{{ url_for('admin.list_courses') }}">退出编辑</a>
				<a class="dropdown-item" href="{{ url_for('auth.logout') }}">退出登录</a>
            </div>
          </li>
        </ul>
      </div>
    </nav>
    {% endif %}
{% endblock navbar %}

{% block page_content %}
   <div class="container">

      <form action="" method="POST" class="form-signin">
          <h2 class="form-signin-heading">Edit an account</h2>

          {{ form.csrf_token }}
          {{ form.hidden_tag() }}


          {{ form.realname(class="form-control", placeholder="真实姓名", value=name, required=True) }}


          {{ form.password(class="form-control", placeholder="新密码", required=True) }}


          {{ form.confirm_password(class="form-control", placeholder="确认新密码") }}

          {{ form.submit(class="btn btn-outline-success my-2 my-sm-0") }}

      </form>




    </div> <!-- /container -->


{% endblock page_content %}

{% block scripts %}
{{ super() }}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='content-static/ie10-viewport-bug-workaround.js') }}"></script>
{% endblock scripts %}